name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::360603920211:role/github
          role-session-name: samplerolesession
          aws-region: us-west-2

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@master
        with:
          repository_name: test_repo
          aws_region: us-west-2
